- src/row.js
- src/table.js
- system-test/bigtable.js
- test/row.js
Fixes #5
There was a missing err.code assignment that was missing in RowError, [Family](https://github.com/googleapis/nodejs-bigtable/blob/443ba9b2bf33de7de6cf49b3a1feb231eda88375/src/family.js#L27-L30) has a similar snippet.
Also added tests around the `row.exists()` method.
> Add missing error code to RowError

- src/table.js
- system-test/bigtable.js
- test/table.js
Fixed data transformation stream to stop processing data on `end` event
Still, need to fix GRPC stream closing.
Fixes #6
> Fix #6 - Allow early ending table/createReadStream

- src/chunktransformer.js
- src/table.js
- system-test/data/read-rows-retry-test.json
- system-test/read-rows.js
- test/chunktransformer.js
- test/table.js
Fixes #7 
~Appropriate docs were updated (if necessary)~
> Smart read retries

- src/chunktransformer.js
- src/table.js
- system-test/data/read-rows-retry-test.json
- system-test/read-rows.js
- test/table.js
Fix broken read row retries
~Appropriate docs were updated (if necessary)~
I used the following to generate some heavy rows:
```js
const bigtable = require('./');
const TABLE_NAME = 'Hello-Bigtable-my-perf';
const COLUMN_FAMILY_NAME = 'cf1';
const COLUMN_NAME = 'greeting';
const INSTANCE_ID = 'helloworld';
const measure = title => {
console.log(`measuring task: ${title}`);
console.time(title);
return () => console.timeEnd(title);
}
let done;
(async () => {
try {
const bigtableClient = bigtable();
const instance = bigtableClient.instance(INSTANCE_ID);
const table = instance.table(TABLE_NAME);
const [tableExists] = await table.exists();
if (tableExists) {
done = measure('Table already exists, delete the table');
await table.delete();
done();
}
const options = {
families: …
```
> Fix read retires.

- src/chunktransformer.js
- test/chunktransformer.js
Fixes #76
- ~[ ] Appropriate docs were updated (if necessary)~
> Fix number decoding

- src/index.js
- src/row.js
- src/table.js
- test/index.js
- test/row.js
- test/table.js
Implement appProfileId support for APIs
> Implemented appProfileId support to bigtable APIs

- src/index.js
- test/index.js
Fixes #75 
This will bypass the `authClient.getProjectId()` call:
- When we already have one from the user (we don't want to override theirs)
- When the user provides `apiEndpoint`
- When the user is using the emulator
> fix: do not require projectId in custom envs

- src/family.js
- system-test/bigtable.js
- test/family.js
Relying on the error code is fragile (and broken). Since the client library
manually controls when this error is thrown, it's the most reliable test
to use for autoCreate.
Fixes #90
~- Appropriate docs were updated (if necessary)~
> Check if Error is FamilyError for autoCreate.

- src/mutation.js
- test/mutation.js
> Default to using client side timestamps

- src/family.js
- test/family.js
> Pass rules when autocreating a family.

- system-test/bigtable.js
> Remove skip flag from truncate test now that GAPIC was regenerated.

- package.json
- src/filter.js
- test/filter.js
> Handle buffers as literal atoms when used as a Filter.

- src/index.js
- system-test/bigtable.js
- test/index.js
Fixes #122
This removes the incoming & outgoing message size limitations set automatically by gRPC.
> Remove max message length requirements.

- system-test/bigtable.js
Union on a GC rule only works when there's more than one rule, this now throws in the system test. This PR fixes that by removing the union property
> Fix system test

- src/mutation.js
`if (!isNaN(num) && isFinite(num)) {` is no longer a valid check if the converted number is valid. Instead:
```js
if (Number.MIN_SAFE_INTEGER < num && num < Number.MAX_SAFE_INTEGER) {
```
is used. Also there's no point in trying to convert the buffer to a number if the buffer length isn't `8`
> Fix broken system test

- .circleci/config.yml
- samples/package-lock.json
> Drop node4 completely

- samples/system-test/instances.test.js
- src/app-profile.js
- src/chunktransformer.js
- src/cluster.js
- src/family.js
- src/filter.js
- src/index.js
- src/instance.js
- src/mutation.js
- src/row.js
- src/table.js
- test/index.js
Fixes #85 
---
This PR should be ready to go. I believe this requires a major semver bump. I figured the test files shouldn't be updated in the same PR. The only thing that really needs to be pointed out is that classes shouldn't be instantiatable without the new keyword:
```js
const client1 = new Bigtable()
const client2 = Bigtable() // Error: Class constructor Foo cannot be invoked without 'new'
```
I was on the fence about requiring people to use the `new` keyword or not, and chose to make it optional. I did this by using a proxy:
```js
Bigtable = new Proxy(Bigtable, {
apply(target, thisArg, argumentsList) {
return new target(...argumentsList);
},
});
```
Let me know if this should be removed. I didn't add that to the semi-private classes since the common case of creating one is …
> Switch src/ to use ES classes

- src/index.js
- src/instance.js
The references should have been for Cloud Bigtable Instances.
> Fixing docs that refered to "Compute Instances"

- src/filter.js
- test/filter.js
Fixes #171 
We were correctly escaping a binary string but after `Filter.convertToRegExpString` was called and returned a string and we then called `Mutation.convertToBytes` with that string, which then assumed utf8 encoding. This PR keeps the filter as a buffer so that `Mutation.convertToBytes` will see it's input as a buffer and just return that buffer
> Fix bad encoded filter

- src/index.js
- test/index.js
Fixes #196  (it's a good idea to open an issue first for discussion)
> fix #196 should not call replaceProjectID token when projectid is passed in option

- src/chunktransformer.js
- src/mutation.js
- src/table.js
- test/chunktransformer.js
- test/mutation.js
- test/row.js
Fixes #185 
The key should be treated as a black box of bytes and not as a utf8 encoded string. 
`Buffer.from('ø', 'binary').toString() === Buffer.from('æ', 'binary').toString()`  
evaluates to true so two consecutive keys like this will cause the chunkTransformer to throw an error. This PR also allows choosing a custom encoding since the `row.data.family` is a hashmap and needs to stringify the value so we can't just leave it as a buffer with `decode = false`
> Fix rowKey being force stringified to utf8

- .cloud-repo-tools.json
- README.md
This works towards issue #224.
The client is ready for Beta.  This PR updates the readme.
> Updating the Readme: Node is now beta

- src/index.js
- test/index.js
Fixes #215
I prefer the docs the way they are (with the `new` keyword) since that way is more idiomatic.
> Allow creating a Bigtable instance without the new keyword.

- samples/hello-world/package.json
- system-test/bigtable.js
- system-test/mutate-rows.js
- system-test/read-rows-acceptance-tests.js
- test/app-profile.js
- test/chunktransformer.js
- test/cluster.js
- test/family.js
- test/filter.js
- test/index.js
- test/instance.js
- test/mutation.js
- test/row.js
- test/table.js
`deepEqual` is causing some issues in PR #247, where the linter seems to prefers `deepStrinctEqual`.  Also, this fixes a strange System test problem from PR #251.
> Use assert.deepStrictEqual instead of deepEqual.

- src/instance.js
> documentation update for getTables

- src/table.js
- test/table.js
> Issue 278 Fix

- samples/document-snippets/.eslintrc.yml
- samples/document-snippets/row.js
- samples/document-snippets/tests/row.js
- src/row.js
Fixes #157 for row.js (it's a good idea to open an issue first for discussion)
> Added example region-tags for row object

- samples/document-snippets/instance.js
- samples/document-snippets/table.js
- samples/document-snippets/tests/instance.js
- samples/document-snippets/tests/table.js
- src/table.js
Fixes #157 for table.js (it's a good idea to open an issue first for discussion)
> Added @example tags to src/table.js

- samples/hello-world/index.js
- samples/hello-world/index.v6.js
+ `index.js`: Use the API correctly (I introduced this bug in 13e3d769962f9301ad73253968d2ae394f7d9766)
+ `index.v6.js`: Make some of the changes from 13e3d769962f9301ad73253968d2ae394f7d9766 (but don't introduce the new bug)
The sample isn't creating the column family for some reason, which means it doesn't work yet, but this change gets it closer to working. Solomon is looking into the column family issue separately.
> Fix "hello world" samples

- src/chunktransformer.js
- test/chunktransformer.js
Fixes #354  (it's a good idea to open an issue first for discussion)
> Fix for Issue#354

- package.json
- synth.py
- system-test/read-rows-acceptance-tests.js
> chore: fix and run the linter

- src/chunktransformer.js
- system-test/read-rows-acceptance-test.json
- test/chunktransformer.js
> Fix for Issue#343

- system-test/bigtable.ts
Fixes #425 
This changes the system test clean up process to only remove stale (1 hour old or greater) instances. This should prevent collisions from parallel system test and sample test runs.
> build: only delete stale test resources

- src/cluster.ts
Fixes #427 (4/21ish)
🤞 
OPR 1 (4/4 @ 6:30pm): Initial draft submit
- Codecov/patch drops to 89.65%
- Codecov/project drops to 95.38% from 95.57%
> refactor(ts): enable noImplicitAny on cluster.ts

- .repo-metadata.json
- README.md
- samples/README.md
Adds a `.repo-metadata.json` which is required for the new docs site, regenerated documentation to match our new templates based on this file.
> docs: add .repo-metadata.json and regenerate docs

- package.json
- src/table.ts
- system-test/bigtable.ts
- system-test/read-rows-acceptance-tests.ts
- system-test/read-rows.ts
- test/table.ts
> fix: cancel streaming grpc request when user ends stream

- src/index.ts
- test/index.ts
Fixes #508
`grpc-js` does not impose a limit to the message length (received or sent).
no longer need to override 
```ts
'grpc.max_send_message_length': -1, 
'grpc.max_receive_message_length': -1,
```
properties.
> refactor: remove unused properties

- package.json
- src/decorateStatus.ts
- src/index.ts
- src/table.ts
- system-test/mutate-rows.ts
- system-test/read-rows.ts
- test/common.ts
- test/index.ts
- test/table.ts
This is more a conversation starter than anything.  The `@google-cloud/common-grpc` module creates a few problems for us:
- `google-gax`, `@google-cloud/common`, and `@google-cloud/common-grpc` all reference `google-auth-library`, which is causing diamond dependency issues when we update things
- We are looking to make broad updates to the transport layers, and I'd like to reduce the number of common core libs we try to use
There is some code copying in here in `decorateStatus` I don't feel great about.  Hoping @alexander-fenster will have suggestions on if/how/where in gax this could live.
With minimal effort, we could also drop the dependency on `@google-cloud/common`.  The error util libraries seem to be the only bits we're using.  We should have a single set of Error classes we're …
> refactor: drop dependency on @google-cloud/common-grpc

- src/mutation.ts
- test/mutation.ts
Instead of checking `MIN_SAFE_INTEGER` and `MAX_SAFE_INTEGER` condition, Added embedded function `Number.isSafeInteger`  to check safe integer.
Fixes #575
> fix: safe integer bounds conversion

- samples/document-snippets/instance.js
- samples/document-snippets/table.js
- src/instance.ts
- src/table.ts
- system-test/bigtable.ts
- test/instance.ts
- test/table.ts
The new features allow user to check and tune [IAM policy](https://cloud.google.com/iam/docs/reference/rest/v1/Policy) for the resource (`instance`, `table`) level:
- `getIamPolicy` - allows a user obtain the current resource IAM policy.
- `setIamPolicy` - allows a user to set resource level IAM policy.
- `testIamPermissions` - allows a user to pass a list of [`permissions`](https://cloud.google.com/bigtable/docs/access-control#permissions) and get back a sub-list of granted permissions.
Fixes #581
> feat: implement instance and table level IAM policy

- src/index.ts
- test/table.ts
While accessing `bigtable.getInstances` with `async` function, it is giving error of return type.
Added overload and related document changes.
Fixes #564
> fix(types): overload for bigtable.getInstances

- src/app-profile.ts
- src/cluster.ts
- src/instance.ts
- src/row.ts
- src/table.ts
One more PR left, then we'll have all the files in `src/` done.
> fix: improve types for instance

- package.json
- src/table.ts
co-authored by: @bcoe 
#678 fails system tests due to a change in pumpify/readable streams. Changes to which tick things are cleaned up on seems to have surfaced an unpiping issue.
> fix(deps): update dependency @google-cloud/common to v3 and handle stream ending

- package.json
- src/index.ts
- system-test/mutate-rows.ts
This is the part where I admit to not understanding how the other stream fix y'all landed works, or if this would be subject to the same kind of problem.  I *do* know that the last 2 usages of `through2` in the codebase cause sample test failures if you swap them out with `PassThrough`.  Can I ask you both to poke holes in this?
> fix: reduce through2 usage

- protos/protos.js
- src/v2/bigtable_instance_admin_client.ts
- src/v2/bigtable_table_admin_client.ts
- synth.metadata
- test/gapic_bigtable_instance_admin_v2.ts
- test/gapic_bigtable_table_admin_v2.ts
- test/gapic_bigtable_v2.ts
For each client method returning a long running operation, a separate method to check its status is added.
Added methods: `checkCreateBackupProgress`, `checkCreateClusterProgress`, `checkCreateInstanceProgress`, `checkCreateTableFromSnapshotProgress`, `checkPartialUpdateInstanceProgress`, `checkRestoreTableProgress`, `checkSnapshotTableProgress`, `checkUpdateAppProfileProgress`, `checkUpdateClusterProgress`.
> feat: check status of long running operation by its name

- src/cluster.ts
- src/index.ts
- src/instance.ts
- system-test/bigtable.ts
- test/cluster.ts
- test/index.ts
- test/instance.ts
BREAKING CHANGE: cluster.setMetadata(): only node count is updatable on an existing cluster; getInstancesCallback/Response: dropped nextQuery property as it is deprecated for this method, exposed failedLocations property; instance.createCluster(): removed unsupported params serveNodes and defaultStorageType
Improve type annotations, some clean up and minor refactoring.
> fix(types)!: improve types in index.ts
