googleapis/nodejs-bigtable

src/row.js
test/row.js

Pass options object to convertFromBytes.

---

src/row.js
test/row.js

Fix #28 table.row().get() dont accept filter in options

---

package.json
protos/google/bigtable/admin/v2/bigtable_instance_admin.proto
protos/google/bigtable/admin/v2/bigtable_table_admin.proto
protos/google/bigtable/admin/v2/common.proto
protos/google/bigtable/admin/v2/instance.proto
protos/google/bigtable/admin/v2/table.proto
protos/google/iam/v1/iam_policy.proto
protos/google/iam/v1/policy.proto
src/v2/bigtable_instance_admin_client.js
src/v2/bigtable_instance_admin_client_config.json
src/v2/bigtable_table_admin_client.js
src/v2/bigtable_table_admin_client_config.json
src/v2/doc/google/bigtable/admin/v2/doc_bigtable_instance_admin.js
src/v2/doc/google/bigtable/admin/v2/doc_bigtable_table_admin.js
src/v2/doc/google/bigtable/admin/v2/doc_instance.js
src/v2/doc/google/bigtable/admin/v2/doc_table.js
src/v2/doc/google/iam/v1/doc_policy.js
src/v2/doc/google/protobuf/doc_duration.js
src/v2/doc/google/protobuf/doc_field_mask.js
src/v2/doc/google/protobuf/doc_timestamp.js
src/v2/index.js
test/gapic-v2-admin.js

Generating GAPIC code for bigtable-admin v2.

feat: GAPIC code for bigtable-admin v2

---

src/chunktransformer.js
system-test/read-rows-acceptance-tests.js

Fixes #44  Patch & ProtoBuf issues

Fix #44 Patch & ProtoBuf issues

---

src/table.js
system-test/mutate-rows.js
test/table.js

Fixes #51 
~[ ] Appropriate docs were updated (if necessary)~

Fix error with broken mutate-rows test

---

samples/package.json

Auto-fixing samples dependency.

chore: make samples depend on the current version

---

system-test/bigtable.js

Related: https://github.com/googleapis/nodejs-bigtable/issues/79
https://circleci.com/gh/googleapis/nodejs-bigtable/2600

Skip "should delete all rows" test

---

src/table.js
test/table.js

feat(table): add prefixes option

---

package-lock.json
samples/package-lock.json
src/v2/bigtable_client.js
src/v2/bigtable_client_config.json
src/v2/bigtable_instance_admin_client.js
src/v2/bigtable_table_admin_client.js
src/v2/bigtable_table_admin_client_config.json
src/v2/index.js

- MutateRow and MutateRows now set to use idempotent retry setting.
- x-goog-request-params header added to options for default requests

Generate GAPIC for BigTable

---

src/row.js
test/row.js

Fixes #98 (it's a good idea to open an issue first for discussion)

added fix for row.get bug issue 

---

src/cluster.js
src/instance.js
test/cluster.js
test/instance.js

Fixes #126  (it's a good idea to open an issue first for discussion)

fix for framing location value

---

package-lock.json
package.json
samples/package-lock.json
samples/package.json

- MutateRow and MutateRows now set to use idempotent retry setting.
- x-goog-request-params header added to options for default requests

bump version to 0.14.0

---

src/chunktransformer.js
src/cluster.js
src/family.js
src/filter.js
src/instance.js
src/mutation.js
src/table.js

Updated with missing documentation

---

.circleci/config.yml
package.json

~Appropriate docs were updated (if necessary)~

Drop support for nodev4.

---

samples/instances.js
samples/package.json
samples/system-test/instances.test.js

Fix samples system tests

---

src/app-profile.js
src/cluster.js
src/instance.js
src/table.js
test/app-profile.js
test/cluster.js
test/instance.js
test/table.js

Issue#137 name vs id fix for instance.js

---

src/family.js
src/instance.js
src/row.js
src/table.js
system-test/bigtable.js
test/family.js
test/index.js
test/instance.js
test/row.js
test/table.js

Partially Fixes #137 (it's a good idea to open an issue first for discussion)

resolved name-vs-id issue for table.js

---

samples/instances.js
src/app-profile.js
src/cluster.js
src/index.js
src/instance.js
system-test/bigtable.js
test/app-profile.js
test/cluster.js
test/index.js
test/instance.js

change id vs. name in Cluster

---

src/cluster.js
system-test/bigtable.js
test/cluster.js

Fixes for system test for swapping id and name for cluster

system tests fixes

---

src/index.js
test/index.js

More changes in index.js for issue #[137](https://github.com/googleapis/nodejs-bigtable/issues/137)
for instance

instance id/name swap in src/test index.js

---

package.json
src/filter.js
test/filter.js

Handle non utf8 buffer filters

---

src/cluster.js

Remove id<->name check for cluster since its not done anywhere else

---

README.md

- Using [campoy/embedmd](https://github.com/campoy/embedmd) to embed quickstart snippet in README
- Updating samples table to reflect samples under samples/

Updating README snippet 

---

src/app-profile.js
src/cluster.js
src/index.js
src/instance.js
src/table.js
test/app-profile.js
test/cluster.js
test/instance.js
test/table.js

New errors for name / id checks in Instance constructors

---

src/index.js
src/instance.js

typo fix for apidoc comment

---

src/family.js
src/table.js
test/family.js
test/table.js

New errors for name / id checks in family constructor

---

test/app-profile.js
test/cluster.js
test/family.js
test/filter.js
test/index.js
test/instance.js
test/mutation.js
test/row.js
test/table.js

There were also a couple of minor string changes for "correctness" between names and ids.

Changing test "var" to "const" and "let"

---

samples/tableadmin.js

Fixing an end tag in tableadmin sample

---

package.json
samples/document-snippets/.eslintrc.yml
samples/document-snippets/instance.js
samples/document-snippets/test.js
src/instance.js

This change was verified thanks to @jmdobry's help with generating the docs.

Added @example tags to src/instance.js (#222)

---

synth.py

build: add repo_name to synth.py

---

package.json
samples/document-snippets/tests/instance.js

Created a `tests` directory for all snippet tests
moved instance-snippet tests

move instance snippet tests to document-snippets/tests

---

src/table.js
test/table.js

System test fix

---

CHANGELOG.md
package.json
samples/package.json

This pull request was generated using releasetool.

Release @google-cloud/bigtable v0.16.0

---

.github/CONTRIBUTING.md

+ Fix links that GitHub wasn't rendering.
+ Remove a TOC item that doesn't exist.
+ Capitalize headings consistently.
+ Remove an unnecessary word.
- [n/a] Code coverage does not decrease (if any source code was changed)
- [n/a] Appropriate docs were updated (if necessary)

Fix some issues in the contributing instructions

---

samples/document-snippets/tests/cluster.js
samples/document-snippets/tests/family.js
samples/document-snippets/tests/instance.js
samples/document-snippets/tests/row.js
samples/document-snippets/tests/table.js

added fix for snippet-test failure

---

src/index.js

fix(docs): fix namespaces causing 404s

---

CHANGELOG.md
package.json
samples/package.json

This pull request was generated using releasetool.

Release @google-cloud/bigtable v1.0.1

---

samples/hello-world/index.js

Updating region tags for consistency across Cloud Bigtable

Region tag consistency

---

package.json
src/app-profile.ts
src/chunktransformer.ts
src/cluster.ts
src/family.ts
src/filter.ts
src/index.ts
src/instance.ts
src/mutation.ts
src/row.ts
src/table.ts
system-test/bigtable.ts
system-test/mutate-rows.ts
system-test/read-rows-acceptance-tests.ts
system-test/read-rows.ts
test/app-profile.ts
test/chunktransformer.ts
test/cluster.ts
test/family.ts
test/filter.ts
test/gapic-v2-admin.ts
test/index.ts
test/instance.ts
test/mutation.ts
test/row.ts
test/table.ts
tsconfig.json
tslint.json

Fixes #427 - hopefully this was what you guys were going for. Majority of the files were changed by the formatter, to explain why so much all at once.

refactor(ts): Linter & Formatter

---

src/chunktransformer.ts

refactor(ts): enable noImplicitAny on chunkTransformer.ts

---

samples/package.json
samples/system-test/write.js
samples/writeBatch.js
samples/writeConditionally.js
samples/writeIncrement.js
samples/writeSimple.js

docs(samples): add conditional, batch, and incremental write samples

---

samples/writeConditionally.js

docs(samples): clean up 'write conditionally' samples

---

src/filter.ts
src/table.ts

fix(docs): contigous to contiguous

---

src/family.ts
src/index.ts
src/table.ts
system-test/read-rows-acceptance-tests.ts
test/table.ts

Incrementally inching towards #635.  This ensures proper types in `table.ts`.

fix: improve typescript types for Table class

---

samples/test/write.js
samples/writeBatch.js
samples/writeConditionally.js
samples/writeIncrement.js
samples/writeSimple.js

Fixes #656
Fixes #657
Fixes #658

test(sample): use unique table IDs

---

src/index.ts
test/index.ts

fix: cluster id store as undefined in createInstance request

---

src/app-profile.ts
src/cluster.ts
src/family.ts
src/filter.ts
src/instance.ts
src/mutation.ts
src/row.ts
test/app-profile.ts
test/chunktransformer.ts
test/cluster.ts
test/family.ts
test/filter.ts
test/index.ts
test/instance.ts
test/mutation.ts
test/row.ts
test/table.ts

refactor: improve types

---

src/row.ts
test/row.ts

fix: row.exists out of memory errors

---

samples/test/instances.test.js

fix: clusterId issue in sample test(should list zones)

---

.github/CODEOWNERS

build: point to team in correct org

---

src/instance.ts

fix(types): stricter types are now enforced

---

src/index.ts

docs: improve jsdocs
